### ISSUE TITLE
"NIMBUS Wake Word Suite" CLI Program

### ISSUE THREAD

**Issue by chidiewenike** [calpoly-csai/CSAI_Voice_Assistant#17]

**Comment by Jason-Ku** [comment]
There may be some tasks to hand off to other software team members here:
* Sai suggested being able to modify the model parameters inside the CLI program
  * Could save the previous model's parameters into a csv file or something to keep track of your iterations and performance (accuracy/loss)

**Comment by chidiewenike** [comment]
@Jason-Ku I love this idea. Definitely add that feature to easily track the model accuracy and loss. Just ensure that this is the test accuracy and loss.

**Comment by Jason-Ku** [comment]
Yep! I really like the idea of an option in the CLI to tweak model parameters, though it could get tedious if you wanted to specify a different number of nodes of layers for whatever reason. I'm guessing that usecase isn't very relevant though

**Comment by Jason-Ku** [comment]
(I can write something up this Sunday to hand it off to a software team member)

**Comment by chidiewenike** [comment]
Wait, the idea is to preload the hyperparameters into the CSV for the program to read from? I thought it was a log of each model you have. Ex: model_25136327236_93.h5  |  Acc: 93 Loss: 1.00  |   Epochs: 20  | Dense Layer #1 Activation: Relu Neurons: 16 | Dense Layer #n ......

**Comment by chidiewenike** [comment]
I supposed you could have both so you don't need to mess with the code to preset those params. That would be pretty useful
